### ISSUE TITLE
Publish new version of plugin

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [gabceb/atom-web-view#32]
Version of plugin is still not bumped - APM still finds old `0.3.0` version since GitHub repository is not tagged and version number in `package.json` is not changed.

**Comment by jjalonso** [comment]
Installing web-view to /Users/jjalonso/.atom/packages ✗
No available version compatible with the installed Atom version: 1.0.2

**Comment by gabceb** [comment]
I have not finished migrating to the 1.0 api. I will push my changes up in hope someone can help

**Comment by Announcement** [comment]
Hey OP, just discovered your proejct, what all needs to be done, I'd love to contribute (and use) your plugin!

**Comment by gabceb** [comment]
@Announcement please do. The plugin has to be updated to work with new Atom API as described in https://github.com/gabceb/atom-web-view/issues/30. I'll work on merging PRs if needed

**Comment by Announcement** [comment]
It's almost completed, please stay tuned every body don't give up just yet. (happy thanksgiving)
